/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package babysitter.esprit.gui;

import babysitter.esprit.dao.classes.OffreMissionDAO;
import babysitter.esprit.dao.interfaces.IoffreMissionDAO;
import babysitter.esprit.entities.OffreMission;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author sassouki
 */
public class JF_OffreMission extends javax.swing.JFrame {

    /**
     * Creates new form JF_OffreMission
     */
    public JF_OffreMission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextAdresse = new javax.swing.JTextField();
        TextHoraire = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDesc = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        B_ajout = new javax.swing.JButton();
        B_AffM = new javax.swing.JButton();
        B_mod = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_Identifiant = new javax.swing.JTextField();
        B_back = new javax.swing.JButton();
        jD = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adresse:");

        jLabel2.setText("Date:");

        jLabel3.setText("Horaire:");

        jLabel4.setText("Description:");

        TextAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAdresseActionPerformed(evt);
            }
        });

        TextDesc.setColumns(20);
        TextDesc.setRows(5);
        jScrollPane1.setViewportView(TextDesc);

        B_ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babysitter/esprit/gui/edit_add.png"))); // NOI18N
        B_ajout.setText("Ajouter");
        B_ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ajoutActionPerformed(evt);
            }
        });

        B_AffM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babysitter/esprit/gui/list (1).png"))); // NOI18N
        B_AffM.setText("Afficher");
        B_AffM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AffMActionPerformed(evt);
            }
        });

        B_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babysitter/esprit/gui/modify.png"))); // NOI18N
        B_mod.setText("Modifier");
        B_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_ajout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(B_AffM)
                .addGap(18, 18, 18)
                .addComponent(B_mod)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_ajout)
                        .addComponent(B_mod))
                    .addComponent(B_AffM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Fiche Offre Mission");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babysitter/esprit/gui/th.jpg"))); // NOI18N

        jLabel7.setText("Identifiant:");

        B_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babysitter/esprit/gui/arrow_left.png"))); // NOI18N
        B_back.setText("Back");
        B_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_back)
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(TextHoraire)
                                    .addComponent(TextAdresse)
                                    .addComponent(TF_Identifiant)
                                    .addComponent(jD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(130, 130, 130)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel5)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jD, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TF_Identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_back)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_AffMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AffMActionPerformed
      JF_AffOffreMission frame=new JF_AffOffreMission();
        setVisible(false);
        frame.setVisible(true);
      
    }//GEN-LAST:event_B_AffMActionPerformed

    private void B_ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ajoutActionPerformed
        OffreMission oM=new OffreMission();
        oM.setAdresse(TextAdresse.getText());
        oM.setDate(jD.getDate().toString());
        oM.setHoraire(TextHoraire.getText());
        oM.setDescription(TextDesc.getText());
        
        IoffreMissionDAO oMdao= OffreMissionDAO.getInstance();
        oMdao.insertOffreMission(oM);
        if ((TextAdresse.getText().length()) == 0) {

JOptionPane.showMessageDialog(this, "le champ adresse est vide", "champ adresse", JOptionPane.ERROR_MESSAGE);
}
        else if (jD.getDate().toString()== null) {

JOptionPane.showMessageDialog(this, "le champ date est vide", "champ date", JOptionPane.ERROR_MESSAGE);
}
         else if ((TextHoraire.getText().length()) == 0) {

JOptionPane.showMessageDialog(this, "le champ horaire est vide", "champ horaire", JOptionPane.ERROR_MESSAGE);
}
        else if ((Pattern.matches("^[a-zA-Z]+$", TextDesc.getText())) || ((TextDesc.getText()).length() == 0)) {
JOptionPane.showMessageDialog(this, "vérifier le champ description", "champ description", JOptionPane.ERROR_MESSAGE);
}
        else{
            JOptionPane.showMessageDialog(this, "Offre Mission ajouter avec succés");
        }
            
         



        
    }//GEN-LAST:event_B_ajoutActionPerformed

    private void TextAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAdresseActionPerformed
       

    }//GEN-LAST:event_TextAdresseActionPerformed

    private void B_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_modActionPerformed
        int IdOffre = 0;
        
        IdOffre=Integer.parseInt(TF_Identifiant.getText()+"");
        OffreMission oM=new OffreMission();
        oM.setAdresse(TextAdresse.getText());
        oM.setDate(jD.getDate().toString());
        oM.setHoraire(TextHoraire.getText());
        oM.setDescription(TextDesc.getText());
        oM.setIdOffre(IdOffre);

 IoffreMissionDAO oMdao= OffreMissionDAO.getInstance();
        oMdao.updateOffreMission(IdOffre,oM);
        
        
    }//GEN-LAST:event_B_modActionPerformed

    private void B_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_backActionPerformed
       JF_Espace es=new JF_Espace();
        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_OffreMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_OffreMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_OffreMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_OffreMission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_OffreMission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AffM;
    private javax.swing.JButton B_ajout;
    private javax.swing.JButton B_back;
    private javax.swing.JButton B_mod;
    private javax.swing.JTextField TF_Identifiant;
    private javax.swing.JTextField TextAdresse;
    private javax.swing.JTextArea TextDesc;
    private javax.swing.JTextField TextHoraire;
    private com.toedter.calendar.JDateChooser jD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
